// ============================================================================
//  LicenseKeys.h -- this app's trust anchor for Amanorsac licensing.
//
//  GENERATED by store-backend/tools/storectl.js. Do not hand-edit.
//
//  This is the PUBLIC half of the shared Amanorsac signing key: an
//  uncompressed NIST P-256 point (0x04 || X || Y). The SAME key signs
//  PerformLive pack manifests/receipts AND every product's license proofs --
//  one trust anchor, company-wide.
//
//  It is compiled in deliberately. If this key lived in a file beside the
//  executable, anyone who could write to that directory could substitute
//  their own key and sign whatever they liked -- precisely what signing
//  exists to prevent.
//
//  ROTATION: keep the old key in a *Previous constant while migrating, so
//  copies of the app already in the wild keep accepting content signed with it.
// ============================================================================
#pragma once
#include <cstdint>

namespace amanorsacstudio
{

// P-256 public key, uncompressed point. 65 bytes.
inline constexpr uint8_t kLicenseSigningKey[] = {
    0x04, 0x17, 0x39, 0xc2, 0xd7, 0x7d, 0x5c, 0x76, 0xae, 0x33, 0xc1, 0x8a,
    0x9e, 0x72, 0x63, 0xc0, 0x85, 0x5a, 0xb7, 0xf2, 0xc7, 0xd8, 0x28, 0x0f,
    0xb4, 0x21, 0xb1, 0x4d, 0x3e, 0xf2, 0xde, 0xde, 0x6e, 0xc4, 0x50, 0x03,
    0x2a, 0x1e, 0x7a, 0x7e, 0xd6, 0x0f, 0xac, 0x13, 0x3b, 0xee, 0x3b, 0x2b,
    0x0e, 0xf2, 0xdc, 0x27, 0x34, 0x5d, 0x9d, 0x1a, 0x32, 0x46, 0x01, 0x67,
    0xdb, 0x55, 0xd0, 0xbf, 0x0e,
};

// Set to true once a real key has been generated. While this is false the app
// refuses to trust any signed content at all, rather than accepting it
// unverified -- fail closed.
inline constexpr bool kLicenseSigningKeyConfigured = true;

} // namespace amanorsacstudio
